name: Lint & Build
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          run_install: true
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
      - name: Lint
        run: pnpm lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          run_install: true
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
      - name: Build
        run: pnpm build
